version: "3"

# Services
services:
 

  # BACKEND
  backend:
    build: ./api
    container_name: api-lumen
    tty: true
    ports:
      - "8080:8080"
    networks:
      - app-network


# Docker Networks
networks:
  app-network:
    name: app-network
    driver: bridge
    external: true
